### ISSUE TITLE
the first version of todo list

### ISSUE THREAD

**Issue by tahminarasoli** [tahminarasoli/todolist#1]
- [X] it should have a place to store todos.
- [X] it shoutld have a way to display todos.
- [X] it shoutld have a way to add a todos.
- [X] it shoutld have a way to edit a todos.
- [X] it shoutld have a way to remove a todos.
