### ISSUE TITLE
the second version of todo list

### ISSUE THREAD

**Issue by tahminarasoli** [tahminarasoli/todolist#3]
- [X] it shoutld have a function to add a todos.
- [X] it shoutld have a function to edit a todos.
- [X] it shoutld have a function to todos.
